# make file generated by gryphel build system
# Enhanced for Apple Silicon (ARM64) with optimization flags

# Architecture and common compiler flags
mk_ArchFlags = -arch arm64
mk_COptionsCommon = -c $(mk_ArchFlags) -Wall -Wmissing-prototypes -Wno-uninitialized -Wundef -Wstrict-prototypes -Icfg/ -Isrc/
# Optimization flags: -Os (optimize for size), -flto (link-time optimization)
mk_COptionsOSGLU = $(mk_COptionsCommon) -Os -flto
mk_COptions = $(mk_COptionsCommon) -Os -flto

.PHONY: TheDefaultOutput clean

TheDefaultOutput : minivmac.app/Contents/MacOS/minivmac

bld/OSGLUCCO.o : src/OSGLUCCO.m src/STRCNENG.h cfg/STRCONST.h src/INTLCHAR.h src/COMOSGLU.h src/CONTROLM.h cfg/CNFGGLOB.h
	gcc "src/OSGLUCCO.m" -o "bld/OSGLUCCO.o" $(mk_COptions) -ObjC
bld/GLOBGLUE.o : src/GLOBGLUE.c cfg/CNFGGLOB.h
	gcc "src/GLOBGLUE.c" -o "bld/GLOBGLUE.o" $(mk_COptions)
bld/M68KITAB.o : src/M68KITAB.c cfg/CNFGGLOB.h
	gcc "src/M68KITAB.c" -o "bld/M68KITAB.o" $(mk_COptions)
bld/MINEM68K.o : src/MINEM68K.c cfg/CNFGGLOB.h
	gcc "src/MINEM68K.c" -o "bld/MINEM68K.o" $(mk_COptions)
bld/VIAEMDEV.o : src/VIAEMDEV.c cfg/CNFGGLOB.h
	gcc "src/VIAEMDEV.c" -o "bld/VIAEMDEV.o" $(mk_COptions)
bld/IWMEMDEV.o : src/IWMEMDEV.c cfg/CNFGGLOB.h
	gcc "src/IWMEMDEV.c" -o "bld/IWMEMDEV.o" $(mk_COptions)
bld/SCCEMDEV.o : src/SCCEMDEV.c cfg/CNFGGLOB.h
	gcc "src/SCCEMDEV.c" -o "bld/SCCEMDEV.o" $(mk_COptions)
bld/RTCEMDEV.o : src/RTCEMDEV.c cfg/CNFGGLOB.h
	gcc "src/RTCEMDEV.c" -o "bld/RTCEMDEV.o" $(mk_COptions)
bld/ROMEMDEV.o : src/ROMEMDEV.c cfg/CNFGGLOB.h
	gcc "src/ROMEMDEV.c" -o "bld/ROMEMDEV.o" $(mk_COptions)
bld/SCSIEMDV.o : src/SCSIEMDV.c cfg/CNFGGLOB.h
	gcc "src/SCSIEMDV.c" -o "bld/SCSIEMDV.o" $(mk_COptions)
bld/SONYEMDV.o : src/SONYEMDV.c cfg/CNFGGLOB.h
	gcc "src/SONYEMDV.c" -o "bld/SONYEMDV.o" $(mk_COptions)
bld/SCRNEMDV.o : src/SCRNEMDV.c cfg/CNFGGLOB.h
	gcc "src/SCRNEMDV.c" -o "bld/SCRNEMDV.o" $(mk_COptions)
bld/MOUSEMDV.o : src/MOUSEMDV.c cfg/CNFGGLOB.h
	gcc "src/MOUSEMDV.c" -o "bld/MOUSEMDV.o" $(mk_COptions)
bld/KBRDEMDV.o : src/KBRDEMDV.c cfg/CNFGGLOB.h
	gcc "src/KBRDEMDV.c" -o "bld/KBRDEMDV.o" $(mk_COptions)
bld/SNDEMDEV.o : src/SNDEMDEV.c cfg/CNFGGLOB.h
	gcc "src/SNDEMDEV.c" -o "bld/SNDEMDEV.o" $(mk_COptions)
bld/PROGMAIN.o : src/PROGMAIN.c cfg/CNFGGLOB.h
	gcc "src/PROGMAIN.c" -o "bld/PROGMAIN.o" $(mk_COptions)

ObjFiles = \
	bld/MINEM68K.o \
	bld/OSGLUCCO.o \
	bld/GLOBGLUE.o \
	bld/M68KITAB.o \
	bld/VIAEMDEV.o \
	bld/IWMEMDEV.o \
	bld/SCCEMDEV.o \
	bld/RTCEMDEV.o \
	bld/ROMEMDEV.o \
	bld/SCSIEMDV.o \
	bld/SONYEMDV.o \
	bld/SCRNEMDV.o \
	bld/MOUSEMDV.o \
	bld/KBRDEMDV.o \
	bld/SNDEMDEV.o \
	bld/PROGMAIN.o \


minivmac.app/Contents/Resources/ICONAPPO.icns : src/ICONAPPO.icns
	rm -fr "minivmac.app/"
	rm -fr "AppTemp/"
	mkdir "AppTemp/"
	mkdir "AppTemp/Contents/"
	mkdir "AppTemp/Contents/MacOS/"
	mkdir "AppTemp/Contents/Resources/"
	mkdir "AppTemp/Contents/Resources/English.lproj/"
	cp "src/ICONAPPO.icns" "AppTemp/Contents/Resources/"
	cp "cfg/Info.plist" "AppTemp/Contents/"
	printf "dummy\n" > "AppTemp/Contents/Resources/English.lproj/dummy.txt"
	printf "APPL????" > "AppTemp/Contents/PkgInfo"
	mv "AppTemp/" "minivmac.app/"

minivmac.app/Contents/MacOS/minivmac : $(ObjFiles) minivmac.app/Contents/Resources/ICONAPPO.icns
	gcc \
		$(mk_ArchFlags) -flto -Os \
		-o "minivmac.app/Contents/MacOS/minivmac" \
		$(ObjFiles) -framework AppKit -framework AudioUnit -framework OpenGL -framework Metal -framework QuartzCore

clean :
	rm -f $(ObjFiles)
	rm -fr "minivmac.app/"
